services:
  - type: web
    name: cosmos-api
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: FRONTEND_URL
        sync: false

  - type: web
    name: cosmos-front
    runtime: static
    buildCommand: npm install && npm run build:frontend
    staticPublishPath: ./frontend
    envVars:
      - key: BACKEND_URL
        sync: false